version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
      - MYSQL_DATABASE=team-member-projects
    ports:
      - 3306:3306
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOSTS=mysql
    container_name: myadmin

  team-member-app:
    image: snegi2020/team-member-image:latest
    environment:
      - DB_USER=user
      - DB_PWD=pass
      - DB_SERVER=mysql
      - DB_NAME=my-app-db
    ports:
      - 8080:8080
    container_name: my-java-app
    
volumes:
  mysql-data:
    driver: local
